version: "3.8"

services: 
    cache:
        image: redis
        ports: 
            - 6379:6379
    database:
        image: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: simple_password
